apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper
  name: zookeeper-service
  namespace: kafka
spec:
  ports:
  - port: 2181
    nodePort: 30181
    targetPort: 2181
  selector:
    app: zookeeper
  type: NodePort
