apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-volume
  name: nginx-volume
spec:
  containers:
    - image: nginx
      name: nginx-volume
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
    - image: busybox
      name: busybox
      command: ['sh', '-c']
      args:
        - while true; do echo $(date) >> /scratch/date.log; sleep 1; done
      volumeMounts:
        - mountPath: /scratch
          name: scratch-volume
 
  volumes:
      - name: scratch-volume
        emptyDir:
          sizeLimit: "500Mi"

